### ISSUE TITLE
Not able to import textanalytics in the edx course notbooks

### ISSUE THREAD

**Issue by aks3743** [jonathandunn/text_analytics#10]
![image](https://user-images.githubusercontent.com/45867750/186393677-27bcc836-9640-456f-aa59-a582de8ed678.png)

**Comment by aks3743** [comment]
https://labs.vocareum.com/main/main.php?m=editor&asnid=769861&stepid=769862&hideNavBar=1

**Comment by jonathandunn** [comment]
This is an issue for the Vocareum set-up within edX, rather than for the package itself. I would suggest resetting the notebook environment (there is a menu on the upper righthand corner for doing this).
