### ISSUE TITLE
Trouble running first notebook, 1.2

### ISSUE THREAD

**Issue by zacharysyoung** [jonathandunn/text_analytics#3]
I wanted to try and run the notebooks locally, so I downloaded **1.2. Accessing the Data** and tried running from Jupyter that was installed with Anaconda3, but I ran into this error:

> `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

I bailed on Anaconda and went for installing everything in a virtualenv:

```sh
% python --version
Python 3.9.1

% pip install jupyterlab
Collecting jupyterlab
  Downloading jupyterlab-3.1.10-py3-none-any.whl (8.5 MB)
...

% pip install textanalytics
...
tensorflow 2.6.0 requires numpy~=1.19.2, but you'll have numpy 1.21.2 which is incompatible.
numba 0.54.0 requires numpy<1.21,>=1.17, but you'll have numpy 1.21.2 which is incompatible.
...
```

so...

```sh
% pip install numpy==1.19.2
...
h5py 3.1.0 requires numpy>=1.19.3; python_version >= "3.9", but you'll have numpy 1.19.2 which is incompatible.
```

so...

```sh
 % pip install numpy==1.19.3
```

re-run Jupyter and the 1.2 notebook, and I'm back to:

> `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

Is there a prescribed setup to use **text_analytics**?

**Comment by damiansastre** [comment]
Hi Zachary, 
Are you trying to run the notebooks on an ARM based processor? 

Also, have you tried uninstalling numpy from your environment and installing the 1.19.2 version? 

try this:
`
pip uninstall numpy `
`
pip install numpy==1.19.2
`
and then re install the package.

Let me know if this helps!

**Comment by zacharysyoung** [comment]
@tagercito, thanks for the quick response! Yes, on an M1 (arm). I updated my question to show I've already done that, seems kinda like I'm stuck in a loop.

And I just tried the full uninstall/install cycle for `numpy==1.19.2`, got the incompatibility error for `h5py` and the initial "value error" from `numpy.ndarray size changed`.

**Comment by damiansastre** [comment]
Tensorflow2 and ARM processors are not best friends.

There are a couple ways you can go around this: 
**The Hard way** :  [Installing Tensorflow from source](https://towardsdatascience.com/installing-tensorflow-on-the-m1-mac-410bb36b776)

**The Slightly easier way** : I created a Dockerfile a couple of months ago for the old version of the package as a workaround. [Github](https://github.com/tagercito/text_analytics_docker) .

I don't have access to my computer right now, but if this doesn't solve the issue I might have another solution to it!

Cheers.

**Comment by zacharysyoung** [comment]
Wow, down the rabbit hole! 🙂

I followed the **Installing Tensorflow from source** instructions you provided, and took a bit of a detour when I got to the section about installing `tensorflow_macos`&mdash;it's out of alpha and has its own ["real" installation now](https://developer.apple.com/metal/tensorflow-plugin/).

```none
(tf_m1) % python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:27:18) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> print(tensorflow.__version__)
2.5.0
```

Not sure if official vs pre-release makes a difference on this error, though:

```none
(tf_m1) % pip install --upgrade -t /Users/zyoung/miniforge3/envs/tf_m1/lib/python3.8/site-packages text_analytics
...
tensorflow-macos 2.5.0 requires six~=1.15.0, but you'll have six 1.16.0 which is incompatible.
...
```

I went and found this file, `tensorflow/tools/pip_package/setup.py` and changed the dependency to `'six ~= 1.16.0'` to try and least get past that pip error. But it still thinks `tensorflow-macos` wants `six ~= 1.15.0`.

I'll get back to this later, thanks!

-   (https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)
-   (https://stackoverflow.com/questions/23969793/setup-py-pip-override-one-of-the-dependencys-sub-dependency-from-requirement)
-   (https://developer.apple.com/metal/tensorflow-plugin/)

**Comment by damiansastre** [comment]
Right, looks like @qhiGenrRvta2 has the same issue(#4) on Intel macbook too.

I will have a closer look tomorrow and update this thread.

**Comment by damiansastre** [comment]
I've created an environment from scratch, looks like there are a couple of things that have to be worked around on M1 processors and also in MacOs in general.

Steps to install the env from scratch:
-  `brew install miniforge`  : this forge distribution allows us to handle multiple CPU archs. _(looks like your env was packed by conda-forge already, so you won't need this step)_
-  `conda create --name text_analytics python=3.9`
-  `conda activate text_analytics`
-  `conda install -c anaconda scikit-learn`
-  `conda install llvmlite`
-  `conda install pandas`
-  `conda install numpy`
-  `conda install numba`
-  And finally: ` pip install git+https://github.com/jonathandunn/text_analytics.git`
```
Python 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:55:16) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from text_analytics import TextAnalytics
>>> ai = TextAnalytics()
>>> ai
<text_analytics.text_analytics.TextAnalytics object at 0x104588970>
```

Let me know how this works @zacharysyoung and @qhiGenrRvta2.
Cheers.

**EDIT**: added lines to python example.

**Comment by zacharysyoung** [comment]
Wow, thank you so much @tagercito for your effort to get this working for us!

But, I still ran into errors, but I wasn't using homebrew, which I've been averse to for years now, but because of your hard work, I'm gonna install homebrew and give it 💯!

Here's my install log, if you're curious what happened w/out homebrew, [install.md](https://github.com/jonathandunn/text_analytics/files/7117624/install.md).

Thanks again, Damian!

**Comment by qhiGenrRvta2** [comment]
Thank you.  I followed the steps suggested in your post, but I'm still getting a ValueError when I import the module.  Error message attached for reference.  
[error_6-Sept-2021.txt](https://github.com/jonathandunn/text_analytics/files/7117729/error_6-Sept-2021.txt)

**Comment by damiansastre** [comment]
@qhiGenrRvta2  would you be able to provide me your conda environment packages? 

Mine looks like this:

```
# Name                    Version                   Build  Channel
absl-py                   0.13.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blis                      0.7.4                    pypi_0    pypi
boto3                     1.18.36                  pypi_0    pypi
botocore                  1.21.36                  pypi_0    pypi
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.17.2               h3422bc3_0    conda-forge
c2xg                      1.0                      pypi_0    pypi
ca-certificates           2021.5.30            h033912b_0    conda-forge
cachetools                4.2.2                    pypi_0    pypi
catalogue                 2.0.6                    pypi_0    pypi
certifi                   2021.5.30                pypi_0    pypi
charset-normalizer        2.0.4                    pypi_0    pypi
clang                     5.0                      pypi_0    pypi
clean-text                0.5.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
corpus-similarity         1.0.1                    pypi_0    pypi
curl                      7.78.0               hc9c2a80_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.5                    pypi_0    pypi
cytoolz                   0.11.0                   pypi_0    pypi
emoji                     1.4.2                    pypi_0    pypi
expat                     2.4.1                hbdafb3b_0    conda-forge
flatbuffers               1.12                     pypi_0    pypi
ftfy                      6.0.3                    pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
gensim                    4.1.0                    pypi_0    pypi
gettext                   0.19.8.1          hea66d9f_1005    conda-forge
git                       2.33.0          pl5321h073b8a2_0    conda-forge
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.39.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
idna                      3.2                      pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
keras                     2.6.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
krb5                      1.19.2               hd92b7a7_0    conda-forge
libblas                   3.9.0           11_osxarm64_openblas    conda-forge
libcblas                  3.9.0           11_osxarm64_openblas    conda-forge
libcurl                   7.78.0               h8fe1914_0    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
liblapack                 3.9.0           11_osxarm64_openblas    conda-forge
libnghttp2                1.43.0               hf3018f0_0    conda-forge
libopenblas               0.3.17          openmp_h5dd58f0_1    conda-forge
libssh2                   1.9.0                hb80f160_6    conda-forge
llvm-openmp               12.0.1               hf3c4609_1    conda-forge
llvmlite                  0.37.0                   pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.4.3                    pypi_0    pypi
murmurhash                1.0.5                    pypi_0    pypi
ncurses                   6.2                  h9aa5885_4    conda-forge
numba                     0.54.0                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.21.2           py38hbf7bb01_0    conda-forge
oauthlib                  3.1.1                    pypi_0    pypi
openssl                   1.1.1l               h0d85af4_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.0                     pypi_0    pypi
pandas                    1.3.2                    pypi_0    pypi
pathy                     0.6.0                    pypi_0    pypi
pcre2                     10.37                hc5de063_0    conda-forge
perl                      5.32.1          0_h9b22ae9_perl5    conda-forge
pillow                    8.3.2                    pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
preshed                   3.0.5                    pypi_0    pypi
protobuf                  3.17.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pydantic                  1.8.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.8.10          h0e5c897_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1                   pypi_0    pypi
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
s3transfer                0.5.0                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                57.5.0                   pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
smart-open                5.2.1                    pypi_0    pypi
spacy                     3.1.2                    pypi_0    pypi
spacy-legacy              3.0.8                    pypi_0    pypi
sqlite                    3.36.0               h72a2b83_0    conda-forge
srsly                     2.4.1                    pypi_0    pypi
stop-words                2018.7.23                pypi_0    pypi
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.6.0                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
textanalytics             1.1                      pypi_0    pypi
thinc                     8.0.9                    pypi_0    pypi
threadpoolctl             2.2.0                    pypi_0    pypi
tk                        8.6.11               he1e0b03_1    conda-forge
toolz                     0.11.1                   pypi_0    pypi
tqdm                      4.62.2                   pypi_0    pypi
typer                     0.3.2                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
wasabi                    0.8.2                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
wordcloud                 1.8.1                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge

```


@zacharysyoung embrace homebrew! it has its good and bad things but usually gets things done.

**Comment by damiansastre** [comment]
@zacharysyoung I have another idea.
The library that is having trouble finding is libcblas when installing numpy for some reason.
```
    Original error was: dlopen(/Users/zyoung/miniforge3/envs/text_analytics/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Library not loaded: @rpath/libcblas.3.dylib
      Referenced from: /Users/zyoung/miniforge3/envs/text_analytics/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
      Reason: image not found
```

can you try installing that before numpy?
`
conda install -c conda-forge libcblas 
`


EDIT: can you also provide your conda package list so we can see the differences?

**Comment by damiansastre** [comment]
@zacharysyoung @qhiGenrRvta2 did you manage to install this?

**Comment by qhiGenrRvta2** [comment]
I’ll get back to you either this evening or tomorrow morning, couldn’t make time yesterday

**Comment by qhiGenrRvta2** [comment]
> can you try installing that before numpy?
> `conda install -c conda-forge libcblas `


After doing this, the import now works for me

**Comment by kdboer1** [comment]
Hi,

I've created a separate conda-environment in which I installed the text_analytics package and I created a separate Juyter-kernel so I can acces the environment in Jupyter on my laptop. Now, I have managed to import the text_analytics package in my own Jupiter Notebook. However, when I try to import the data with the code provided in the Workbench (see below), I get a FileNotFoundError: FileNotFoundError: [Errno 2] No such file or directory: 'data\Wordclouds.Business_Insider.gz'.

My Question: As I have imported the text_analytics package succesfully. How do I also succesfully access the data provided and used in the Notebooks related to this course? Can I find these files online, or did I not correctly install the text_analytics package that prevent's the code from accessing the datasets?

Hope you can help me out with this :)

Thanks!

Klaas

-- Code copied from Workbench -- 
file = os.path.join(ai.data_dir, "Wordclouds.Business_Insider.gz") 
df = pd.read_csv(file, index_col = 0)

**Comment by zacharysyoung** [comment]
Hey @tagercito, I'm sorry for getting back to you so late... I got a little overwhelmed by all this...

Anyways, I went back to my original miniforge install (not w/homebrew), tried inserting the **libcblas** install, and still got an error installing text_analytics... looks like the same error, too, [install_history.txt](https://github.com/jonathandunn/text_analytics/files/7188038/install_history.txt).

At this time, I'll be happy to follow along online and am not going to try and get this working locally.

Thank you for all your time and effort, I know you're putting in a lot here!

**Comment by jonathandunn** [comment]
Klaas,

As far as accessing the data from the text analytics course, that isn't currently possible outside of the edX environment.

Cheers,

Jonathan

**Comment by ktavabi** [comment]
@jonathandunn EdX is charging ~$300 to watch you play with kindergarten toys! The vocareum-hosted notebooks are advertised as noob resources to go through YOUR course material. I've spent just the past hour troubleshooting the first cell in the first lab notebook. This is 🐂💩 
cheers
Kambiz
