### ISSUE TITLE
'import text_analytics' fails with ValueError on macOS

### ISSUE THREAD

**Issue by qhiGenrRvta2** [jonathandunn/text_analytics#4]
I installed the text_analytics package based on the instructions from Lab 1.2:
````pip3 install git+https://github.com/jonathandunn/text_analytics.git````
and tried to run the first part of the lab code locally.  It does not work, failing with a ValueError.

The following code reproduces the bug for me.  I'm using an Intel mac running macOS 11.5:

```
#!/usr/bin/env python3
from text_analytics import text_analytics
print('Done')
```

A copy of the full error message is here: [error.txt](https://github.com/jonathandunn/text_analytics/files/7111241/error.txt)

**Comment by damiansastre** [comment]
Hi @qhiGenrRvta2 we are working on this issue on this thread  [#3](https://github.com/jonathandunn/text_analytics/issues/3#issue-988387044) 

edit: 

In reference to this error:

` 
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
`

**Comment by qhiGenrRvta2** [comment]
Thanks - and sorry for the duplicate report
