### ISSUE TITLE
metaclass conflict error

### ISSUE THREAD

**Issue by Estella85** [jonathandunn/text_analytics#7]
Hello all,

after I run the first step of lab1.2 

from text_analytics import text_analytics
import os
import pandas as pd
print("Done!")

I got the following error "TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases".

I'm new to phyton, so, how can I solve this?

In addition to that, Is there a way I can download and see the structure of data we have to work on (e.g. "Wordclouds.Business_Insider.gz")? I cannot find it in this package https://github.com/jonathandunn/text_analytics.

Thank you
Alessandra

**Comment by damiansastre** [comment]
Hi Alessandra,

can you try changing the line:

from text_analytics import text_analytics

to

from text_analytics import TextAnalytics

let me know if it works.

**Comment by Estella85** [comment]
Hi tagercito,

thank you for your support. I tried but I got the same error.

**Comment by jonathandunn** [comment]
Kia ora Alessandra,

I'm assuming you are referring to this notebook: https://github.com/jonathandunn/corpus_analysis/blob/main/Lab%201.2.%20Accessing%20the%20Corpora.ipynb

First, the data should be available here: https://doi.org/10.24433/CO.3402613.v1

Second, in terms of the error itself, I've not seen that one before. Are you referring to a pip installed version of text_analytics or a local version?

Cheers,

Jonathan
